name: Check inochi-creator releases

on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 * * * *" # repeat every hour
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 

env:
  FLATPAK_ID: com.inochi2d.inochi-creator

jobs:
  release-check:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08

    strategy:
      matrix:
        branch: [ "master", "beta" ] # list all branches to check

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Fix git
        run: |
          git config --global --add safe.directory /__w/${{ env.FLATPAK_ID }}/${{ env.FLATPAK_ID }}

      - name: Run flatpak-external-data-checker
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        with:
          args: --edit-only ./${{ env.FLATPAK_ID }}.yml

      - name: Check updated
        id: is-updated 
        run: |
          git status -s -uno
          [ -z "$(git status -s -uno)" ] || echo "::set-output name=updated::true"

      - name: Install deps
        if: steps.is-updated.outputs.updated
        run: |
          dnf -y install dub ldc python3-pyyaml

      - name: Update dependencies
        if: steps.is-updated.outputs.updated
        run: |
          ./update-dependencies.sh

      - name: Reset yml
        run: |
          git checkout -- ${FLATPAK_ID}.yml *.xml

      - name: Recheck and open PR
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork ${{ env.FLATPAK_ID }}.yml
